name: Build and publish Docker images on ghcr.io (nightly/new release)

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    # Publish "nightly" build as release
    - cron: '15 9 * * *'
  push:
    # Publish semver tags as releases.
    tags: [ '*.*.*' ]
  # or on button click
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY_HOST: ghcr.io
  # Use github.repository (<account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository and build Docker image
        uses: actions/checkout@v3
        # Necessary to build it locally for boca-web and boca-jail
        #run: docker build -t boca-base . -f docker/dev/base/Dockerfile

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY_HOST }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata (boca-base)
        id: meta_base
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY_HOST }}/${{ env.IMAGE_NAME }}/boca-base

      - name: Extract Docker metadata (boca-web)
        id: meta_web
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY_HOST }}/${{ env.IMAGE_NAME }}/boca-web

      - name: Extract Docker metadata (boca-jail)
        id: meta_jail
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY_HOST }}/${{ env.IMAGE_NAME }}/boca-jail

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push boca-base image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/dev/base/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_base.outputs.tags }}
          labels: ${{ steps.meta_base.outputs.labels }}
          
      - name: Build boca-base image only (necessary to build boca-web and boca-jail)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/dev/base/Dockerfile
          push: false
          tags: boca-base
          
      - name: Build and push boca-web image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/dev/web/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_web.outputs.tags }}
          labels: ${{ steps.meta_web.outputs.labels }}

      - name: Build and push boca-jail image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/dev/jail/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_jail.outputs.tags }}
          labels: ${{ steps.meta_jail.outputs.labels }}
